CREATE TABLE SimorghPortalZero972.dbo.wp_wpforo_forums (
    forumid INT PRIMARY KEY,
    title NVARCHAR(255) NULL,
    slug NVARCHAR(255) NULL,
    description NVARCHAR(MAX) NULL,
    parentid INT NULL DEFAULT 0,
    icon NVARCHAR(255) NULL DEFAULT 'fas fa-comments',
    cover NVARCHAR(255) NULL DEFAULT '0',
    cover_height INT NULL DEFAULT 150,
    last_topicid INT NULL DEFAULT 0,
    last_postid INT NULL DEFAULT 0,
    last_userid INT NULL DEFAULT 1,
    last_post_date DATETIME NULL DEFAULT '2024-10-07 08:39:32',
    topics INT DEFAULT 0,
    posts INT DEFAULT 0,
    permissions NVARCHAR(MAX) NULL DEFAULT 'a:5:{i:1;s:4:"full";i:2;s:9:"moderator";i:3;s:8:"standard";i:4;s:9:"read_only";i:5;s:8:"standard";}',
    meta_key NVARCHAR(255) NULL,
    meta_desc NVARCHAR(500) NULL,
    status TINYINT DEFAULT 1,
    is_cat BIT DEFAULT 1,
    layout NVARCHAR(50) NULL DEFAULT '4',
    [order] INT NULL DEFAULT 0,
    color NVARCHAR(50) NULL DEFAULT '#888888'
);
